version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
      python: 3.8
    commands:
      - pip install aws-sam-cli
  build:
    commands:
      - sam build
      - sam package --template-file template.yaml --s3-bucket aws-sam-cli-managed-default-samclisourcebucket-xco3nyxwukgo --output-template-file packaged.yaml
  post_build:
    commands:
      - sam deploy --template-file packaged.yaml --stack-name proleadsoft-demo --capabilities CAPABILITY_IAM --region us-east-1
      - sam deploy --template-file packaged.yaml --stack-name proleadsoft-demo --capabilities CAPABILITY_IAM --region us-west-1
